import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { format, resolveConfig } from "prettier";

import { NORMALIZATION_VERSION, normalizeText, xhtmlToText } from "../../src/fidelity/index.js";
import { locateQuote } from "../../src/query/tools.js";
import { quoteEdgeCases, quoteEdgeDiv } from "../../test/query/quote-edge-cases.js";

// Publishes the query service's own quote-edge decisions over the worked examples of
// docs/design/epi-mcp-query-service.md ("The quote-edge rule"), so that a test double of
// `verify_quote` in another language can be held to them. The agent's fake query service
// (agent/tests/fake_query_service.py) applies the rule and agent/tests/test_quote_edge.py
// asserts it reproduces every answer and offset here; `npm run contracts:check` regenerates the
// file and fails on drift, so a change to the rule that is not carried into the double fails CI.
//
// Each section text goes through exactly what `verifyQuote` does to a stored narrative
// (xhtmlToText, then normalizeText), and each quote through what it does to a quote
// (normalizeText); `locateQuote` is the function `verifyQuote` decides with. Nothing here is
// expected: `result` is what the rule answered. test/query/acceptance.test.ts is where the
// answers are held to the design's expectations.
//
// Deterministic like scripts/contracts/export-fixtures.ts: no clock, no randomness, Prettier
// formatting resolved from the repository config.

const output = path.resolve("test/fixtures/contracts");
await mkdir(output, { recursive: true });
const prettierOptions = { ...(await resolveConfig(output)), parser: "json" as const };

const sections = quoteEdgeCases.map((section) => {
  const { cut, whole } = section;
  const normalized = normalizeText(xhtmlToText(quoteEdgeDiv(section)));
  const quotes = [...cut, ...whole].map((raw) => {
    const quote = normalizeText(raw);
    const located = locateQuote(normalized, quote);
    return located === undefined
      ? { quote, result: "no-match" as const }
      : { quote, result: "match" as const, ...located };
  });
  return { text: normalized, quotes };
});

const document = {
  description:
    "The query service's quote-edge decisions (src/query/tools.ts locateQuote) over the worked examples in test/query/quote-edge-cases.ts. Generated by scripts/contracts/export-quote-edge-cases.ts; offsets are code points in the normalised text.",
  normalizationVersion: NORMALIZATION_VERSION,
  sections,
};

await writeFile(
  path.join(output, "quote-edge-cases.json"),
  await format(JSON.stringify(document, null, 2), prettierOptions),
);

console.log(
  `Exported ${sections.reduce((count, section) => count + section.quotes.length, 0)} quote-edge decisions in ${output}`,
);
