options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west4
  _REPOSITORY: ema-flow
  _IMAGE_TAG: manual

steps:
  - id: build-app-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/worker:${_IMAGE_TAG}
      - .

  - id: build-validator-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.validator
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/validator:${_IMAGE_TAG}
      - .

  - id: build-query-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.query
      - --tag
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/query:${_IMAGE_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/worker:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/validator:${_IMAGE_TAG}
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/query:${_IMAGE_TAG}
