"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  fidelity-report.schema.json

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Status(StrEnum):
    passed = "passed"
    failed = "failed"


class Issue(RootModel[str]):
    root: Annotated[str, Field(max_length=256)]


class Summary(BaseModel):
    model_config = ConfigDict(extra="forbid")
    total: Annotated[int, Field(ge=0, le=9007199254740991)]
    verified: Annotated[int, Field(ge=0, le=9007199254740991)]


class Coverage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    pageCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    bodyCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    coveredCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    uncoveredGaps: Annotated[int, Field(ge=0, le=9007199254740991)]


class NormalizationVersion(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Version of docs/fidelity-normalization.md the hashes were computed under.",
            pattern="^fidelity-norm\\/[0-9]+\\.[0-9]+\\.[0-9]+$",
        ),
    ]


class Sha256Hex(RootModel[str]):
    root: Annotated[
        str, Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$")
    ]


class SourceKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Canonical SmPC section identifier from the mapping manifest, e.g. smpc.4.2.posology.",
            pattern="^[a-z0-9]+(?:\\.[a-z0-9]+)*$",
        ),
    ]


class SectionStatus(StrEnum):
    verified = "verified"
    mismatch = "mismatch"
    span_not_found = "span-not-found"
    invalid_provenance = "invalid-provenance"
    missing_provenance = "missing-provenance"
    malformed_narrative = "malformed-narrative"


class DiffHint(BaseModel):
    model_config = ConfigDict(extra="forbid")
    expectedLength: Annotated[int, Field(ge=0, le=9007199254740991)]
    actualLength: Annotated[int, Field(ge=0, le=9007199254740991)]
    firstDifferingOffset: Annotated[int, Field(ge=0, le=9007199254740991)]
    commonSuffixLength: Annotated[int, Field(ge=0, le=9007199254740991)]
    expectedWordCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    actualWordCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    expectedSha256: Sha256Hex
    actualSha256: Sha256Hex


class SectionResult(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sourceKey: SourceKey
    path: Annotated[
        str, Field(pattern="^Composition\\.section\\[[0-9]+\\](?:\\.section\\[[0-9]+\\])*$")
    ]
    status: SectionStatus
    spanCount: Annotated[int, Field(ge=0, le=9007199254740991)]
    reason: Annotated[str | None, Field(pattern="^[a-z][a-z-]{0,40}$")] = None
    details: DiffHint | None = None
    normalizedTextSha256: Sha256Hex | None = None


class FidelityReport(BaseModel):
    model_config = ConfigDict(extra="forbid")
    reportVersion: Literal["1.0.0"]
    normalizationVersion: NormalizationVersion
    extractedTextSha256: Sha256Hex
    narrativeBindingSha256: Sha256Hex
    status: Status
    sections: list[SectionResult]
    issues: list[Issue]
    summary: Summary
    coverage: Coverage
    reportHash: Sha256Hex


class Model(RootModel[FidelityReport]):
    root: FidelityReport
