"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  ingestion-provenance.schema.json

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Sha256Hex(RootModel[str]):
    root: Annotated[
        str, Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$")
    ]


class MediaType(StrEnum):
    application_pdf = "application/pdf"
    application_vnd_openxmlformats_officedocument_wordprocessingml_document = (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )


class Token(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Identifier: letters, digits, and . _ : / @ + - only.",
            pattern="^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,127}$",
        ),
    ]


class StorageUri(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Cloud Storage object URI (gs://bucket/object).",
            max_length=512,
            pattern="^gs:\\/\\/[a-z0-9][a-z0-9._-]{1,220}[a-z0-9]\\/[A-Za-z0-9._/-]{1,256}$",
        ),
    ]


class ExtractedTextRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    uri: StorageUri
    sha256: Sha256Hex
    extractorVersion: Token


class Uuid(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class ToolVersion(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    version: Token


class ModelRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    provider: Token
    id: Token


class PromptTemplateRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    id: Token
    version: Token
    sha256: Sha256Hex


class TerminologyServiceRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    version: Token
    snapshotSha256: Sha256Hex


class SourceKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Canonical SmPC section identifier from the mapping manifest, e.g. smpc.4.2.posology.",
            pattern="^[a-z0-9]+(?:\\.[a-z0-9]+)*$",
        ),
    ]


class SourceSpan(BaseModel):
    model_config = ConfigDict(extra="forbid")
    page: Annotated[int, Field(gt=0, le=9007199254740991)]
    startOffset: Annotated[int, Field(ge=0, le=9007199254740991)]
    endOffset: Annotated[int, Field(gt=0, le=9007199254740991)]
    textSha256: Sha256Hex


class TargetPath(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=256,
            pattern="^[A-Za-z][A-Za-z0-9]*(?:\\[\\d+\\])?(?:\\.[A-Za-z][A-Za-z0-9]*(?:\\[\\d+\\])?)*$",
        ),
    ]


class DecisionAction(StrEnum):
    extracted_verbatim = "extracted-verbatim"
    code_mapped = "code-mapped"
    defaulted_by_rule = "defaulted-by-rule"
    human_edited = "human-edited"
    rejected = "rejected"


class HttpUrl(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="http(s) URL without whitespace; may carry |version.",
            max_length=256,
            pattern="^https?:\\/\\/[A-Za-z0-9.-]{1,253}(?::\\d{1,5})?(?:[/?#][A-Za-z0-9._~:/?#@!$&'()*+,;=%|-]*)?$",
        ),
    ]


class DecisionReason(StrEnum):
    boundary_correction = "boundary-correction"
    code_correction = "code-correction"
    metadata_correction = "metadata-correction"
    not_applicable = "not-applicable"
    unreadable_source = "unreadable-source"
    out_of_scope = "out-of-scope"
    duplicate = "duplicate"


class NormalizationVersion(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Version of docs/fidelity-normalization.md the hashes were computed under.",
            pattern="^fidelity-norm\\/\\d+\\.\\d+\\.\\d+$",
        ),
    ]


class FidelityStatus(StrEnum):
    passed = "passed"
    failed = "failed"


class SourceSystemRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    documentId: Token
    versionId: Token | None = None


class ExtractionTooling(BaseModel):
    model_config = ConfigDict(extra="forbid")
    extractionRunId: Uuid
    serviceVersion: Token
    parser: ToolVersion
    model: ModelRef | None = None
    promptTemplate: PromptTemplateRef | None = None
    terminologyService: TerminologyServiceRef | None = None


class SectionProvenance(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sourceKey: SourceKey
    spans: Annotated[list[SourceSpan], Field(min_length=1)]
    narrativeDivSha256: Sha256Hex
    normalizedTextSha256: Sha256Hex


class TerminologyRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    system: HttpUrl
    code: Token
    version: Token | None = None
    lookupId: Token


class FidelitySummary(BaseModel):
    model_config = ConfigDict(extra="forbid")
    normalizationVersion: NormalizationVersion
    status: FidelityStatus
    sectionsChecked: Annotated[int, Field(ge=0, le=9007199254740991)]
    sectionsMatched: Annotated[int, Field(ge=0, le=9007199254740991)]
    narrativeBindingSha256: Sha256Hex
    reportSha256: Sha256Hex
    reportUri: StorageUri | None = None


class SourceDocument(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sha256: Sha256Hex
    byteLength: Annotated[int, Field(gt=0, le=9007199254740991)]
    mediaType: MediaType
    filename: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._ -]{0,254}$")]
    pageCount: Annotated[int | None, Field(gt=0, le=9007199254740991)] = None
    sourceSystem: SourceSystemRef | None = None
    storageUri: StorageUri | None = None
    extractedText: ExtractedTextRef


class StructuringDecision(BaseModel):
    model_config = ConfigDict(extra="forbid")
    target: TargetPath
    sourceKey: SourceKey | None = None
    action: DecisionAction
    ruleId: Token | None = None
    terminologyRef: TerminologyRef | None = None
    editorId: Token | None = None
    reason: DecisionReason | None = None


class IngestionProvenance(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sourceDocument: SourceDocument
    extraction: ExtractionTooling
    sections: Annotated[list[SectionProvenance], Field(min_length=1)]
    decisions: Annotated[list[StructuringDecision], Field(min_length=1)]
    fidelity: FidelitySummary


class Model(RootModel[IngestionProvenance]):
    root: IngestionProvenance
