"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  ingestion-provenance.schema.json

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import ConfigDict, Field, RootModel, StrictInt, StrictStr
from typing_extensions import TypeAliasType
from zone_a.contract_model import ContractModel


class Sha256Hex(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$"),
    ]


class MediaType(StrEnum):
    application_pdf = "application/pdf"
    application_vnd_openxmlformats_officedocument_wordprocessingml_document = (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )


class Token(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Identifier: letters, digits, and . _ : / @ + - only.",
            pattern="^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,127}$",
        ),
    ]


class StorageUri(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Cloud Storage object URI (gs://bucket/object).",
            max_length=512,
            pattern="^gs:\\/\\/[a-z0-9][a-z0-9._-]{1,220}[a-z0-9]\\/[A-Za-z0-9._/-]{1,256}$",
        ),
    ]


class ExtractedTextRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    uri: StorageUri
    sha256: Sha256Hex
    extractorVersion: Token


class Authority(StrEnum):
    EMA = "EMA"
    synthetic = "synthetic"


class AuthorityId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="A lower-case GUID.",
            pattern="^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
        ),
    ]


class PinnedFile(ContractModel):
    model_config = ConfigDict(extra="forbid")
    id: AuthorityId
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]


class PictureReference(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(pattern="^~\\/_entity\\/annotation\\/[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$"),
    ]


class HttpUrl(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="http(s) URL without whitespace; may carry |version.",
            max_length=256,
            pattern="^https?:\\/\\/[A-Za-z0-9.-]{1,253}(?::[0-9]{1,5})?(?:[/?#][A-Za-z0-9._~:/?#@!$&'()*+,;=%|-]*)?$",
        ),
    ]


class SectionPath(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern="^Composition(?:\\.section\\[[0-9]{1,4}\\]){1,16}$")]


class Document(ContractModel):
    model_config = ConfigDict(extra="forbid")
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    filename: Annotated[StrictStr, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._ -]{0,254}$")]
    storageUri: StorageUri


class Document1(StrEnum):
    smpc = "smpc"
    pl = "pl"


class View(StrEnum):
    accepted = "accepted"
    original = "original"


AssignmentsAdditionalProperty = TypeAliasType(
    "AssignmentsAdditionalProperty", Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
)


class SourceKey(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Canonical SmPC section identifier from the mapping manifest, e.g. smpc.4.2.posology.",
            pattern="^[a-z0-9]+(?:\\.[a-z0-9]+)*$",
        ),
    ]


class RecomputeVersions(ContractModel):
    model_config = ConfigDict(extra="forbid")
    recompute: Token
    reader: Token
    format: Token
    structurer: Token
    registryVersion: Token
    mappingVersion: Token
    builder: Token


class Uuid(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class ToolVersion(ContractModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    version: Token


class ModelRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    provider: Token
    id: Token


class PromptTemplateRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    id: Token
    version: Token
    sha256: Sha256Hex


class TerminologyServiceRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    version: Token
    snapshotSha256: Sha256Hex


class SourceSpan(ContractModel):
    model_config = ConfigDict(extra="forbid")
    page: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    startOffset: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    endOffset: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    textSha256: Sha256Hex


class TargetPath(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=256,
            pattern="^[A-Za-z][A-Za-z0-9]*(?:\\[[0-9]+\\])?(?:\\.[A-Za-z][A-Za-z0-9]*(?:\\[[0-9]+\\])?)*$",
        ),
    ]


class SourcePath(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            max_length=256,
            pattern="^(?:List|Bundle|Composition)(?:\\.[A-Za-z][A-Za-z0-9]*(?:\\[(?:[0-9]{1,4}|[A-Za-z][A-Za-z0-9]*)\\])?)*$",
        ),
    ]


class DecisionAction(StrEnum):
    extracted_verbatim = "extracted-verbatim"
    code_mapped = "code-mapped"
    defaulted_by_rule = "defaulted-by-rule"
    human_edited = "human-edited"
    rejected = "rejected"


class TerminologyRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    system: HttpUrl
    code: Token
    version: Token | None = None
    lookupId: Token


class DecisionReason(StrEnum):
    boundary_correction = "boundary-correction"
    code_correction = "code-correction"
    metadata_correction = "metadata-correction"
    not_applicable = "not-applicable"
    unreadable_source = "unreadable-source"
    out_of_scope = "out-of-scope"
    duplicate = "duplicate"


class NormalizationVersion(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Version of docs/fidelity-normalization.md the hashes were computed under.",
            pattern="^fidelity-norm\\/[0-9]+\\.[0-9]+\\.[0-9]+$",
        ),
    ]


class FidelityStatus(StrEnum):
    passed = "passed"
    failed = "failed"


class SourceSystemRef(ContractModel):
    model_config = ConfigDict(extra="forbid")
    name: Token
    documentId: Token
    versionId: Token | None = None


class Index(ContractModel):
    model_config = ConfigDict(extra="forbid")
    id: AuthorityId
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    epiId: Token
    versionNumber: Token
    metaVersionId: Token
    status: Literal["current"]


class SectionPage(ContractModel):
    model_config = ConfigDict(extra="forbid")
    page: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    path: SectionPath
    code: Token


class ImportRequest(ContractModel):
    model_config = ConfigDict(extra="forbid")
    authority: Authority
    documentId: AuthorityId
    indexId: AuthorityId
    language: Literal["en"]


class Picture1(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["fetched"]
    reference: PictureReference
    url: HttpUrl
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]


class Picture2(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["not-drawn"]
    reference: PictureReference
    evidence: Token


class Picture(RootModel[Picture1 | Picture2]):
    root: Picture1 | Picture2


class SectionPage1(ContractModel):
    model_config = ConfigDict(extra="forbid")
    page: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    key: SourceKey
    code: Token


class RecomputeRequest(ContractModel):
    model_config = ConfigDict(extra="forbid")
    document: Document1
    view: View | None
    part: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    assignments: dict[SourceKey, AssignmentsAdditionalProperty]
    versions: RecomputeVersions


class ExtractionTooling(ContractModel):
    model_config = ConfigDict(extra="forbid")
    extractionRunId: Uuid
    serviceVersion: Token
    parser: ToolVersion
    model: ModelRef | None = None
    promptTemplate: PromptTemplateRef | None = None
    terminologyService: TerminologyServiceRef | None = None


class SectionProvenance(ContractModel):
    model_config = ConfigDict(extra="forbid")
    sourceKey: SourceKey
    spans: Annotated[list[SourceSpan], Field(min_length=1)]
    narrativeDivSha256: Sha256Hex
    normalizedTextSha256: Sha256Hex


class StructuringDecision(ContractModel):
    model_config = ConfigDict(extra="forbid")
    target: TargetPath
    sourceKey: SourceKey | None = None
    sourceField: SourcePath | None = None
    action: DecisionAction
    ruleId: Token | None = None
    terminologyRef: TerminologyRef | None = None
    editorId: Token | None = None
    reason: DecisionReason | None = None


class FidelitySummary(ContractModel):
    model_config = ConfigDict(extra="forbid")
    normalizationVersion: NormalizationVersion
    status: FidelityStatus
    sectionsChecked: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    sectionsMatched: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    narrativeBindingSha256: Sha256Hex
    reportSha256: Sha256Hex
    reportUri: StorageUri | None = None


class DrawnSourceDocument(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["drawn"]
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    mediaType: MediaType
    filename: Annotated[StrictStr, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._ -]{0,254}$")]
    pageCount: Annotated[StrictInt | None, Field(gt=0, le=9007199254740991)] = None
    sourceSystem: SourceSystemRef | None = None
    storageUri: StorageUri | None = None
    extractedText: ExtractedTextRef


class AuthoritySourceDocument(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["authority-publication"]
    mediaType: Literal["application/fhir+json"]
    authority: Authority
    request: ImportRequest
    document: PinnedFile
    index: Index
    pictures: Annotated[list[Picture], Field(max_length=500)]
    sectionPages: Annotated[list[SectionPage], Field(max_length=2000, min_length=1)]
    extractedText: ExtractedTextRef


class CertifiedWordSourceDocument(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Literal["certified-word"]
    mediaType: Literal["application/vnd.openxmlformats-officedocument.wordprocessingml.document"]
    document: Document
    recompute: RecomputeRequest
    changes: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    sectionPages: Annotated[list[SectionPage1], Field(max_length=2000, min_length=1)]
    extractedText: ExtractedTextRef


class SourceDocument(
    RootModel[DrawnSourceDocument | AuthoritySourceDocument | CertifiedWordSourceDocument]
):
    root: DrawnSourceDocument | AuthoritySourceDocument | CertifiedWordSourceDocument


class IngestionProvenance(ContractModel):
    model_config = ConfigDict(extra="forbid")
    sourceDocument: SourceDocument
    extraction: ExtractionTooling
    sections: Annotated[list[SectionProvenance], Field(min_length=1)]
    decisions: Annotated[list[StructuringDecision], Field(min_length=1)]
    fidelity: FidelitySummary


class Model(RootModel[IngestionProvenance]):
    root: IngestionProvenance
