"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  run-manifest.schema.json

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Kind(StrEnum):
    fixture = "fixture"
    healthcare_api = "healthcare-api"
    document = "document"


class Sha256Hex(RootModel[str]):
    root: Annotated[
        str, Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$")
    ]


class Uuid(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class IsoDateTime(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="RFC 3339 timestamp with Z or a numeric offset.",
            pattern="^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))$",
        ),
    ]


class PackageRef(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="FHIR package id#version.",
            max_length=256,
            pattern="^[A-Za-z][A-Za-z0-9-]*(?:\\.[A-Za-z0-9-]+)*#\\d+\\.\\d+\\.\\d+(?:-[0-9A-Za-z.-]+)?$",
        ),
    ]


class ManifestPackage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    package: PackageRef
    sha256: Sha256Hex


class HttpUrl(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="http(s) URL without whitespace; may carry |version.",
            max_length=256,
            pattern="^https?:\\/\\/[A-Za-z0-9.-]{1,253}(?::\\d{1,5})?(?:[/?#][A-Za-z0-9._~:/?#@!$&'()*+,;=%|-]*)?$",
        ),
    ]


class ManifestTransformation(BaseModel):
    model_config = ConfigDict(extra="forbid")
    inputHash: Sha256Hex
    outputHash: Sha256Hex
    decisions: Annotated[int, Field(ge=0, le=9007199254740991)]


class ManifestRuntime(BaseModel):
    model_config = ConfigDict(extra="forbid")
    sourceCommit: Annotated[str, Field(max_length=1024, min_length=1)]
    imageDigest: Annotated[str, Field(max_length=1024, min_length=1)]
    workflowRevision: Annotated[str, Field(max_length=1024, min_length=1)]
    validatorImageDigest: Annotated[str, Field(max_length=1024, min_length=1)]


class SourceKind(StrEnum):
    drawn = "drawn"
    authority_publication = "authority-publication"


class Status(StrEnum):
    passed = "passed"


class Coverage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    pageCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    bodyCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    coveredCodePoints: Annotated[int, Field(ge=0, le=9007199254740991)]
    uncoveredGaps: Annotated[int, Field(ge=0, le=9007199254740991)]


class GraphType(StrEnum):
    type1 = "type1"
    type2 = "type2"


class Token(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Identifier: letters, digits, and . _ : / @ + - only.",
            pattern="^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,127}$",
        ),
    ]


class NormalizationVersion(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Version of docs/fidelity-normalization.md the hashes were computed under.",
            pattern="^fidelity-norm\\/\\d+\\.\\d+\\.\\d+$",
        ),
    ]


class PrincipalId(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$")]


class ApproverRole(StrEnum):
    content_reviewer = "content-reviewer"
    qa_reviewer = "qa-reviewer"


class AttestationMethod(StrEnum):
    api_attestation = "api-attestation"
    manual_record = "manual-record"


class ApprovalMeaning(StrEnum):
    reviewed_fidelity_and_structure = "reviewed-fidelity-and-structure"


class RecordRef(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._:/#?=&%+-]{0,511}$")]


class Authority(StrEnum):
    EMA = "EMA"
    synthetic = "synthetic"


class AuthorityStatus(StrEnum):
    pilot = "pilot"


class AuthorityId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="A lower-case GUID.",
            pattern="^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
        ),
    ]


class FetchedItem(BaseModel):
    model_config = ConfigDict(extra="forbid")
    url: HttpUrl
    sha256: Sha256Hex
    byteLength: Annotated[int, Field(ge=0, le=9007199254740991)]
    fetchedAt: IsoDateTime
    evidenceUri: Annotated[str | None, Field(max_length=1024, min_length=1)] = None


class AuthorityFetch(BaseModel):
    model_config = ConfigDict(extra="forbid")
    importerVersion: Token
    fetched: Annotated[list[FetchedItem], Field(min_length=2)]


class Source1(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Kind
    resource: Annotated[str, Field(max_length=1024, min_length=1)]
    hash: Sha256Hex


class ManifestPersistence(BaseModel):
    model_config = ConfigDict(extra="forbid")
    targetStore: Annotated[str, Field(max_length=1024, min_length=1)]
    transactionSha256: Sha256Hex


class Source(BaseModel):
    model_config = ConfigDict(extra="forbid")
    kind: Kind
    resource: Annotated[str, Field(max_length=1024, min_length=1)]
    hash: Sha256Hex


class ManifestStandards(BaseModel):
    model_config = ConfigDict(extra="forbid")
    fhir: Literal["5.0.0"]
    globalEpiPackage: PackageRef
    emaPackage: Literal["EUePI#1.0.0"]
    qrdTemplate: Annotated[str, Field(max_length=1024, min_length=1)]
    mappingVersion: Annotated[str, Field(max_length=1024, min_length=1)]
    packages: Annotated[list[ManifestPackage], Field(min_length=1)]


class ManifestValidation(BaseModel):
    model_config = ConfigDict(extra="forbid")
    preflightErrors: Annotated[int, Field(ge=0, le=9007199254740991)]
    officialValidationExecuted: bool
    officialProfileErrors: Annotated[int, Field(ge=0, le=9007199254740991)]
    cloudValidationExecuted: bool
    cloudProfileErrors: Annotated[int, Field(ge=0, le=9007199254740991)]
    profiles: list[HttpUrl]


class Fidelity(BaseModel):
    model_config = ConfigDict(extra="forbid")
    status: Status
    normalizationVersion: NormalizationVersion
    sectionsChecked: Annotated[int, Field(ge=0, le=9007199254740991)]
    sectionsMatched: Annotated[int, Field(ge=0, le=9007199254740991)]
    reportSha256: Sha256Hex
    narrativeBindingSha256: Sha256Hex
    coverage: Coverage


class AttestedApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")
    approverId: PrincipalId
    approverRole: ApproverRole
    approvedAt: IsoDateTime
    method: AttestationMethod
    meaning: ApprovalMeaning
    approvedContentSha256: Sha256Hex
    recordRef: RecordRef | None = None


class Publication(BaseModel):
    model_config = ConfigDict(extra="forbid")
    epiId: Token
    documentId: AuthorityId
    indexId: AuthorityId
    versionNumber: Token
    procedureNumber: Token
    authorityTimestamp: IsoDateTime


class AuthorityApproval(BaseModel):
    model_config = ConfigDict(extra="forbid")
    method: Literal["authority-publication"]
    meaning: Literal["authority-publication-imported"]
    authority: Authority
    authorityStatus: AuthorityStatus
    publication: Publication
    requestedBy: PrincipalId
    requestedAt: IsoDateTime
    approvedContentSha256: Sha256Hex


class Approval(RootModel[AttestedApproval | AuthorityApproval]):
    root: AttestedApproval | AuthorityApproval


class IngestionEvidence(BaseModel):
    model_config = ConfigDict(extra="forbid")
    submissionId: Uuid
    contractVersion: Literal["2.0.0"]
    sourceKind: SourceKind
    graphType: GraphType
    allowSyntheticSources: bool
    sourceDocumentSha256: Sha256Hex
    extractionRunId: Uuid
    parser: Token
    modelId: Token | None = None
    promptTemplateVersion: Token | None = None
    fidelity: Fidelity
    approval: Approval
    authority: AuthorityFetch | None = None
    provenanceResourceId: Uuid


class AuthorisedRunManifest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schemaVersion: Literal["4.0.0"]
    source: Source1
    runId: Uuid
    startedAt: IsoDateTime
    completedAt: IsoDateTime
    standards: ManifestStandards
    validation: ManifestValidation
    transformation: ManifestTransformation
    runtime: ManifestRuntime
    ingestion: IngestionEvidence | None = None
    status: Literal["authorised"]
    dryRun: Literal[False]
    persistence: ManifestPersistence


class ValidatedRunManifest(BaseModel):
    model_config = ConfigDict(extra="forbid")
    schemaVersion: Literal["4.0.0"]
    source: Source
    runId: Uuid
    startedAt: IsoDateTime
    completedAt: IsoDateTime
    standards: ManifestStandards
    validation: ManifestValidation
    transformation: ManifestTransformation
    runtime: ManifestRuntime
    ingestion: IngestionEvidence | None = None
    status: Literal["validated"]
    dryRun: Literal[True]


class RunManifest(RootModel[ValidatedRunManifest | AuthorisedRunManifest]):
    root: ValidatedRunManifest | AuthorisedRunManifest


class Model(RootModel[RunManifest]):
    root: RunManifest
