"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  run-manifest.schema.json

from enum import StrEnum
from typing import Annotated, Literal

from pydantic import ConfigDict, Field, RootModel, StrictBool, StrictInt, StrictStr
from zone_a.contract_model import ContractModel


class Kind(StrEnum):
    fixture = "fixture"
    healthcare_api = "healthcare-api"
    document = "document"


class Sha256Hex(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$"),
    ]


class Uuid(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class IsoDateTime(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="RFC 3339 timestamp with Z or a numeric offset.",
            pattern="^(?:(?:[0-9][0-9][2468][048]|[0-9][0-9][13579][26]|[0-9][0-9]0[48]|[02468][048]00|[13579][26]00)-02-29|[0-9]{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12][0-9]|3[01])|(?:0[469]|11)-(?:0[1-9]|[12][0-9]|30)|(?:02)-(?:0[1-9]|1[0-9]|2[0-8])))T(?:(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](?:\\.[0-9]+)?(?:Z|([+-](?:[01][0-9]|2[0-3]):[0-5][0-9])))$",
        ),
    ]


class PackageRef(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="FHIR package id#version.",
            max_length=256,
            pattern="^[A-Za-z][A-Za-z0-9-]*(?:\\.[A-Za-z0-9-]+)*#[0-9]+\\.[0-9]+\\.[0-9]+(?:-[0-9A-Za-z.-]+)?$",
        ),
    ]


class Token(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Identifier: letters, digits, and . _ : / @ + - only.",
            pattern="^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,127}$",
        ),
    ]


class ManifestPackage(ContractModel):
    model_config = ConfigDict(extra="forbid")
    package: PackageRef
    sha256: Sha256Hex


class HttpUrl(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="http(s) URL without whitespace; may carry |version.",
            max_length=256,
            pattern="^https?:\\/\\/[A-Za-z0-9.-]{1,253}(?::[0-9]{1,5})?(?:[/?#][A-Za-z0-9._~:/?#@!$&'()*+,;=%|-]*)?$",
        ),
    ]


class ManifestTransformation(ContractModel):
    model_config = ConfigDict(extra="forbid")
    inputHash: Sha256Hex
    outputHash: Sha256Hex
    decisions: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class GitCommit(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(description="Full lower-case hexadecimal git commit id.", pattern="^[0-9a-f]{40}$"),
    ]


class ImageDigest(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern="^sha256:[0-9a-f]{64}$")]


class SourceKind(StrEnum):
    drawn = "drawn"
    authority_publication = "authority-publication"


class Status(StrEnum):
    passed = "passed"


class Coverage(ContractModel):
    model_config = ConfigDict(extra="forbid")
    pageCodePoints: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    bodyCodePoints: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    coveredCodePoints: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    uncoveredGaps: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class GraphType(StrEnum):
    type1 = "type1"
    type2 = "type2"


class NormalizationVersion(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Version of docs/fidelity-normalization.md the hashes were computed under.",
            pattern="^fidelity-norm\\/[0-9]+\\.[0-9]+\\.[0-9]+$",
        ),
    ]


class PrincipalId(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._:/-]{0,127}$")]


class ApproverRole(StrEnum):
    content_reviewer = "content-reviewer"
    qa_reviewer = "qa-reviewer"


class AttestationMethod(StrEnum):
    api_attestation = "api-attestation"
    manual_record = "manual-record"


class ApprovalMeaning(StrEnum):
    reviewed_fidelity_and_structure = "reviewed-fidelity-and-structure"


class RecordRef(RootModel[StrictStr]):
    root: Annotated[StrictStr, Field(pattern="^[A-Za-z0-9][A-Za-z0-9._:/#?=&%+-]{0,511}$")]


class Authority(StrEnum):
    EMA = "EMA"
    synthetic = "synthetic"


class AuthorityStatus(StrEnum):
    pilot = "pilot"


class AuthorityId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="A lower-case GUID.",
            pattern="^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
        ),
    ]


class FetchedItem(ContractModel):
    model_config = ConfigDict(extra="forbid")
    url: HttpUrl
    sha256: Sha256Hex
    byteLength: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    fetchedAt: IsoDateTime
    evidenceUri: Annotated[StrictStr | None, Field(max_length=1024, min_length=1)] = None


class AuthorityFetch(ContractModel):
    model_config = ConfigDict(extra="forbid")
    importerVersion: Token
    fetched: Annotated[list[FetchedItem], Field(min_length=2)]


class Source1(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Kind
    resource: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    hash: Sha256Hex


class ManifestPersistence(ContractModel):
    model_config = ConfigDict(extra="forbid")
    targetStore: Token
    transactionSha256: Sha256Hex


class Source(ContractModel):
    model_config = ConfigDict(extra="forbid")
    kind: Kind
    resource: Annotated[StrictStr, Field(max_length=1024, min_length=1)]
    hash: Sha256Hex


class ManifestStandards(ContractModel):
    model_config = ConfigDict(extra="forbid")
    fhir: Literal["5.0.0"]
    globalEpiPackage: PackageRef
    emaPackage: Literal["EUePI#1.0.0"]
    qrdTemplate: Token
    mappingVersion: Token
    packages: Annotated[list[ManifestPackage], Field(min_length=1)]


class ManifestValidation(ContractModel):
    model_config = ConfigDict(extra="forbid")
    preflightErrors: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    officialValidationExecuted: StrictBool
    officialProfileErrors: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    cloudValidationExecuted: StrictBool
    cloudProfileErrors: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    profiles: list[HttpUrl]


class ManifestRuntime(ContractModel):
    model_config = ConfigDict(extra="forbid")
    sourceCommit: GitCommit | Literal["development"]
    imageDigest: ImageDigest | Literal["development"]
    validatorImageDigest: ImageDigest | Literal["development"]
    workflowRevision: Token


class Fidelity(ContractModel):
    model_config = ConfigDict(extra="forbid")
    status: Status
    normalizationVersion: NormalizationVersion
    sectionsChecked: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    sectionsMatched: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    reportSha256: Sha256Hex
    narrativeBindingSha256: Sha256Hex
    coverage: Coverage


class AttestedApproval(ContractModel):
    model_config = ConfigDict(extra="forbid")
    approverId: PrincipalId
    approverRole: ApproverRole
    approvedAt: IsoDateTime
    method: AttestationMethod
    meaning: ApprovalMeaning
    approvedContentSha256: Sha256Hex
    recordRef: RecordRef | None = None


class Publication(ContractModel):
    model_config = ConfigDict(extra="forbid")
    epiId: Token
    documentId: AuthorityId
    indexId: AuthorityId
    versionNumber: Token
    procedureNumber: Token
    authorityTimestamp: IsoDateTime


class AuthorityApproval(ContractModel):
    model_config = ConfigDict(extra="forbid")
    method: Literal["authority-publication"]
    meaning: Literal["authority-publication-imported"]
    authority: Authority
    authorityStatus: AuthorityStatus
    publication: Publication
    requestedBy: PrincipalId
    requestedAt: IsoDateTime
    approvedContentSha256: Sha256Hex


class Approval(RootModel[AttestedApproval | AuthorityApproval]):
    root: AttestedApproval | AuthorityApproval


class IngestionEvidence(ContractModel):
    model_config = ConfigDict(extra="forbid")
    submissionId: Uuid
    contractVersion: Literal["2.0.0"]
    sourceKind: SourceKind
    graphType: GraphType
    allowSyntheticSources: StrictBool
    sourceDocumentSha256: Sha256Hex
    extractionRunId: Uuid
    parser: Token
    modelId: Token | None = None
    promptTemplateVersion: Token | None = None
    fidelity: Fidelity
    approval: Approval
    authority: AuthorityFetch | None = None
    provenanceResourceId: Uuid


class AuthorisedRunManifest(ContractModel):
    model_config = ConfigDict(extra="forbid")
    schemaVersion: Literal["5.0.0"]
    source: Source1
    runId: Uuid
    startedAt: IsoDateTime
    completedAt: IsoDateTime
    standards: ManifestStandards
    validation: ManifestValidation
    transformation: ManifestTransformation
    runtime: ManifestRuntime
    ingestion: IngestionEvidence | None = None
    status: Literal["authorised"]
    dryRun: Literal[False]
    persistence: ManifestPersistence


class ValidatedRunManifest(ContractModel):
    model_config = ConfigDict(extra="forbid")
    schemaVersion: Literal["5.0.0"]
    source: Source
    runId: Uuid
    startedAt: IsoDateTime
    completedAt: IsoDateTime
    standards: ManifestStandards
    validation: ManifestValidation
    transformation: ManifestTransformation
    runtime: ManifestRuntime
    ingestion: IngestionEvidence | None = None
    status: Literal["validated"]
    dryRun: Literal[True]


class RunManifest(RootModel[ValidatedRunManifest | AuthorisedRunManifest]):
    root: ValidatedRunManifest | AuthorisedRunManifest


class Model(RootModel[RunManifest]):
    root: RunManifest
