"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  run-request.schema.json

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Uuid(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern="^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$"
        ),
    ]


class AddressableFhirId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="FHIR id that begins with a letter or digit, so a single URL path segment.",
            pattern="^[A-Za-z0-9][A-Za-z0-9\\-.]{0,63}$",
        ),
    ]


class StorageUri(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="Cloud Storage object URI (gs://bucket/object).",
            max_length=512,
            pattern="^gs:\\/\\/[a-z0-9][a-z0-9._-]{1,220}[a-z0-9]\\/[A-Za-z0-9._/-]{1,256}$",
        ),
    ]


class Sha256Hex(RootModel[str]):
    root: Annotated[
        str, Field(description="Lower-case hexadecimal SHA-256 digest.", pattern="^[0-9a-f]{64}$")
    ]


class RunRequest1(BaseModel):
    model_config = ConfigDict(extra="forbid")
    source: Literal["fixture"]
    runId: Uuid | None = None


class RunRequest2(BaseModel):
    model_config = ConfigDict(extra="forbid")
    source: Literal["healthcare-api"]
    bundleId: AddressableFhirId
    runId: Uuid | None = None


class SubmissionRef(BaseModel):
    model_config = ConfigDict(extra="forbid")
    uri: StorageUri
    sha256: Sha256Hex


class RunRequest3(BaseModel):
    model_config = ConfigDict(extra="forbid")
    source: Literal["document"]
    submissionRef: SubmissionRef
    runId: Uuid | None = None


class RunRequest(RootModel[RunRequest1 | RunRequest2 | RunRequest3]):
    root: Annotated[
        RunRequest1 | RunRequest2 | RunRequest3,
        Field(
            description="Request to run the deterministic pipeline. Strict: an unrecognised field is a rejection, never a silently ignored one."
        ),
    ]


class Model(RootModel[RunRequest]):
    root: RunRequest
