"""Generated pydantic models. Do not edit.

Regenerate with ``uv run python scripts/generate_models.py``; ``--check`` fails the build when a
committed module is out of date with ``contracts/generated/``.
"""

# generated by datamodel-codegen:
#   filename:  source-document-text.schema.json

from typing import Annotated

from pydantic import ConfigDict, Field, RootModel, StrictInt, StrictStr
from zone_a.contract_model import ContractModel


class Page(ContractModel):
    model_config = ConfigDict(extra="forbid")
    page: Annotated[StrictInt, Field(gt=0, le=9007199254740991)]
    text: Annotated[StrictStr, Field(max_length=500000)]
    bodyStart: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]
    bodyEnd: Annotated[StrictInt, Field(ge=0, le=9007199254740991)]


class Token(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            description="Identifier: letters, digits, and . _ : / @ + - only.",
            pattern="^[A-Za-z0-9][A-Za-z0-9._:/@+-]{0,127}$",
        ),
    ]


class SourceDocumentText(ContractModel):
    model_config = ConfigDict(extra="forbid")
    extractorVersion: Token
    pages: Annotated[list[Page], Field(max_length=2000, min_length=1)]


class Model(RootModel[SourceDocumentText]):
    root: SourceDocumentText
