"""The fake's ``verify_quote`` decides as the real service does, answer for answer.

``test/fixtures/contracts/quote-edge-cases.json`` is the query service's own quote-edge rule
(``src/query/tools.ts`` ``locateQuote``) applied to the worked examples of the design, exported
by ``scripts/contracts/export-quote-edge-cases.ts`` and regenerated by ``npm run
contracts:check``, which fails on drift. Before 2026-09-22 the fake matched any substring, so a
chunk the real service refuses passed here, and the splitter's cuts inside "1 000 000" and after
"≥" went unseen by every test.
"""

from __future__ import annotations

import contextlib
import re
from typing import Any

import pytest
from google.adk.agents.readonly_context import ReadonlyContext
from google.adk.tools.tool_context import ToolContext

from verifiable_answer_agent import quote_edge
from verifiable_answer_agent.quote_edge import locate_quote
from verifiable_answer_agent.tools import build_query_toolset, read_tool_result

from .conftest import config_for, invocation_context
from .fake_query_service import (
    BUNDLE_ID,
    NORMALIZATION_VERSION,
    REPOSITORY_ROOT,
    FakeQueryService,
    quote_edge_cases,
    synthetic_section,
)

CASE_KEY = "smpc.4.1"


def _decisions() -> list[tuple[str, dict[str, Any]]]:
    return [
        (section["text"], quote)
        for section in quote_edge_cases()["sections"]
        for quote in section["quotes"]
    ]


def test_the_export_is_at_the_fakes_normalisation_version_and_covers_both_answers() -> None:
    assert quote_edge_cases()["normalizationVersion"] == NORMALIZATION_VERSION
    answers = [quote["result"] for _, quote in _decisions()]
    assert answers.count("match") > 10
    assert answers.count("no-match") > 10
    # The two cuts the splitter used to make are among them, and the service refuses both.
    refused = {quote["quote"] for _, quote in _decisions() if quote["result"] == "no-match"}
    assert {"Give up to 1 000", "000 IU daily.", "30 ml/min."} <= refused


@pytest.mark.parametrize(
    ("name", "ported"),
    [
        ("QUOTE_OPENERS", quote_edge.QUOTE_OPENERS),
        ("QUOTE_CLOSERS", quote_edge.QUOTE_CLOSERS),
        ("SPACED_SIGNS", quote_edge.SPACED_SIGNS),
    ],
)
def test_each_character_set_is_the_services_own(name: str, ported: frozenset[str]) -> None:
    # The worked examples do not touch every character of every set; the source does.
    source = (REPOSITORY_ROOT / "src" / "query" / "tools.ts").read_text(encoding="utf-8")
    found = re.search(rf"const {name} = new Set\(\[(.*?)\]\);", source, re.DOTALL)
    assert found is not None, name
    literals = re.findall(r"\"((?:[^\"\\]|\\.)*)\"|'((?:[^'\\]|\\.)*)'", found.group(1))
    assert frozenset(double or single for double, single in literals) == ported


def test_the_rule_reproduces_every_answer_and_offset_the_service_gave() -> None:
    for text, quote in _decisions():
        located = locate_quote(text, quote["quote"])
        if quote["result"] == "no-match":
            assert located is None, (text, quote)
        else:
            assert located == (quote["startOffset"], quote["endOffset"]), (text, quote)


async def test_the_fakes_verify_quote_answers_as_the_service_did(
    query_service: FakeQueryService,
) -> None:
    toolset = build_query_toolset(config_for(query_service.url))
    context = invocation_context()
    try:
        tools = {tool.name: tool for tool in await toolset.get_tools(ReadonlyContext(context))}
        for section in quote_edge_cases()["sections"]:
            # Each text is the whole of the store, as each is one section's narrative there.
            query_service.sections = {CASE_KEY: synthetic_section(CASE_KEY, section["text"])}
            for quote in section["quotes"]:
                raw = await tools["verify_quote"].run_async(
                    args={"bundleId": BUNDLE_ID, "sourceKey": CASE_KEY, "quote": quote["quote"]},
                    tool_context=ToolContext(context),
                )
                result = read_tool_result("verify_quote", raw)
                assert result.value is not None, quote
                assert result.value["result"] == quote["result"], quote
                match = result.value.get("match")
                if quote["result"] == "match":
                    assert match is not None
                    assert (match["startOffset"], match["endOffset"]) == (
                        quote["startOffset"],
                        quote["endOffset"],
                    ), quote
                else:
                    assert match is None, quote
    finally:
        with contextlib.suppress(Exception):
            await toolset.close()
