"""The fake's ``verify_quote`` decides as the real service does, answer for answer.

``test/fixtures/contracts/quote-edge-cases.json`` is the query service's own quote-edge rule
(``src/query/tools.ts`` ``locateQuote``) applied to the worked examples of the design, exported
by ``scripts/contracts/export-quote-edge-cases.ts`` and regenerated by ``npm run
contracts:check``, which fails on drift. Before 2026-09-22 the fake matched any substring, so a
chunk the real service refuses passed here, and the splitter's cuts inside "1 000 000" and after
"≥" went unseen by every test.
"""

from __future__ import annotations

import contextlib
import re
from typing import Any

import pytest
from google.adk.agents.readonly_context import ReadonlyContext
from google.adk.tools.tool_context import ToolContext

from verifiable_answer_agent import quote_edge
from verifiable_answer_agent.quote_edge import is_gap, locate_quote
from verifiable_answer_agent.tools import build_query_toolset, read_tool_result

from .conftest import config_for, invocation_context
from .fake_query_service import (
    BUNDLE_ID,
    NORMALIZATION_VERSION,
    REPOSITORY_ROOT,
    FakeQueryService,
    quote_edge_cases,
    quote_is_refused,
    synthetic_section,
)

CASE_KEY = "smpc.4.1"


def _decisions() -> list[tuple[str, dict[str, Any]]]:
    return [
        (section["text"], quote)
        for section in quote_edge_cases()["sections"]
        for quote in section["quotes"]
    ]


def test_the_export_is_at_the_fakes_normalisation_version_and_covers_both_answers() -> None:
    assert quote_edge_cases()["normalizationVersion"] == NORMALIZATION_VERSION
    # The version the post-check accepts is the one the service exported its decisions under.
    assert quote_edge.NORMALIZATION_VERSION == NORMALIZATION_VERSION
    answers = [quote["result"] for _, quote in _decisions()]
    assert answers.count("match") > 10
    assert answers.count("no-match") > 10
    # The two cuts the splitter used to make are among them, and the service refuses both.
    refused = {quote["quote"] for _, quote in _decisions() if quote["result"] == "no-match"}
    assert {"Give up to 1 000", "000 IU daily.", "30 ml/min."} <= refused


@pytest.mark.parametrize(
    ("name", "ported"),
    [
        ("QUOTE_OPENERS", quote_edge.QUOTE_OPENERS),
        ("QUOTE_CLOSERS", quote_edge.QUOTE_CLOSERS),
        ("PLAIN_PUNCTUATION", quote_edge.PLAIN_PUNCTUATION),
        ("POSTFIX_SIGNS", quote_edge.POSTFIX_SIGNS),
    ],
)
def test_each_character_set_is_the_services_own(name: str, ported: frozenset[str]) -> None:
    # The worked examples do not touch every character of every set; the source does.
    source = (REPOSITORY_ROOT / "src" / "query" / "tools.ts").read_text(encoding="utf-8")
    found = re.search(rf"const {name} = new Set\(\[(.*?)\]\);", source, re.DOTALL)
    assert found is not None, name
    # Comments inside the set are not entries: a quoted character in one would hide a removal.
    body = re.sub(r"//[^\n]*", "", found.group(1))
    literals = re.findall(r"\"((?:[^\"\\]|\\.)*)\"|'((?:[^'\\]|\\.)*)'", body)
    assert frozenset(double or single for double, single in literals) == ported


def test_the_rule_reproduces_every_answer_and_offset_the_service_gave() -> None:
    for text, quote in _decisions():
        located = locate_quote(text, quote["quote"])
        if quote["result"] == "no-match":
            assert located is None, (text, quote)
        else:
            assert located == (quote["startOffset"], quote["endOffset"]), (text, quote)


async def test_the_fakes_verify_quote_answers_as_the_service_did(
    query_service: FakeQueryService,
) -> None:
    toolset = build_query_toolset(config_for(query_service.url))
    context = invocation_context()
    try:
        tools = {tool.name: tool for tool in await toolset.get_tools(ReadonlyContext(context))}
        for section in quote_edge_cases()["sections"]:
            # Each text is the whole of the store, as each is one section's narrative there.
            query_service.sections = {CASE_KEY: synthetic_section(CASE_KEY, section["text"])}
            for quote in section["quotes"]:
                raw = await tools["verify_quote"].run_async(
                    args={"bundleId": BUNDLE_ID, "sourceKey": CASE_KEY, "quote": quote["quote"]},
                    tool_context=ToolContext(context),
                )
                result = read_tool_result("verify_quote", raw)
                assert result.value is not None, quote
                assert result.value["result"] == quote["result"], quote
                match = result.value.get("match")
                if quote["result"] == "match":
                    assert match is not None
                    assert (match["startOffset"], match["endOffset"]) == (
                        quote["startOffset"],
                        quote["endOffset"],
                    ), quote
                else:
                    assert match is None, quote
    finally:
        with contextlib.suppress(Exception):
            await toolset.close()


def test_the_fake_refuses_the_quotes_the_service_refuses() -> None:
    """The test double answers ``invalid-request`` where ``src/query/tools.ts`` does.

    Since fidelity-norm/3.0.0 that includes a quote carrying a table's grid markers or a
    picture's U+FFFC, and a quote of gaps alone: such a quote could join two rows, or quote nothing
    a reader sees.
    """
    table = "Dose table \ufdd0 \ufdd2 \ufdd3 Adults \ufdd3 10 mg \ufdd1 end."
    refused = (
        table,
        "\ufdd3",
        "a \ufffc b",
        "dose\x00 is",
        "dose\u202e is",
        "   ",
        # Quotes that normalise to nothing: invisible characters, and a line-start bullet.
        "\u00ad",
        "\u200b",
        "\u2060",
        "\ufeff",
        " \u00ad ",
        "\u200b  ",
        "\u00ad\n",
        "\u00ad\r\n",
        "\n\u2022 ",
        "\n\u2022 \u25cf ",
        "\n\u2022\n",
        # Quotes of gaps alone (section 6): content spaces, blank glyphs, ignorable code points.
        "\u2009",
        "\u205f",
        " \u2063 ",
        "\u2800",
        "\u205f\u200d",
        "\U000e0020",
        "\n\u2022 \u2009",
        "\u1878\ua4c5",
        # Section 2 from fidelity-norm/3.0.0: the interlinear annotation controls and the
        # prepended concatenation marks.
        "Take 10 \ufff9000",
        "10\u070f000",
        "\U000110bd",
    )
    for quote in refused:
        assert quote_is_refused(quote), repr(quote)
    accepted = (
        "Adults",
        "10 mg",
        "\ufdcf x",
        "\ufdf0",
        "Take 2 \u2022 10 mg",
        # A bullet that step 4 keeps: at the start of the text, at the end, or on a tab line.
        "\n\u2022",
        "\u2022 ",
        "\n\u2022\t",
        # A bullet after a thin space is not at the line's start, so step 4 keeps it.
        "\n\u2009\u2022 ",
        "\u2009x",
    )
    for quote in accepted:
        assert not quote_is_refused(quote), repr(quote)


# fidelity-norm/3.0.0 sections 2 and 6, as the specification writes them (the service is held to
# the same lists in test/fidelity-lists.test.ts): dropping one entry from the double or the port
# fails here.
_FORBIDDEN_FROM_3_0_0 = (
    0x0600, 0x0601, 0x0602, 0x0603, 0x0604, 0x0605, 0x06DD, 0x070F, 0x0890, 0x0891, 0x08E2,
    0xFFF9, 0xFFFA, 0xFFFB, 0x110BD, 0x110CD,
)  # fmt: skip
_BLANK_GLYPHS = (0x1878, 0x18AA, 0x2800, 0xA4A2, 0xA4A3, 0xA4B4, 0xA4C1, 0xA4C5)


def test_the_double_refuses_every_code_point_section_2_adds() -> None:
    for code_point in _FORBIDDEN_FROM_3_0_0:
        assert quote_is_refused(f"dose {chr(code_point)} is"), hex(code_point)


def test_every_blank_glyph_is_a_gap() -> None:
    for code_point in _BLANK_GLYPHS:
        assert is_gap(chr(code_point)), hex(code_point)


def test_a_long_run_of_brackets_and_spaces_is_read_in_one_pass() -> None:
    # Past the bounded walk the one-pass reading takes over, and answers the same.
    signed = "CrCl <" + " (" * 400 + " 30 ml/min"
    assert locate_quote(signed, "30 ml/min") is None
    plain = "Dose" + " (" * 400 + " 30 ml/min"
    assert locate_quote(plain, "30 ml/min") is not None
    # Without the whole text a walk that runs too long counts as a sign (the splitter reads with
    # the whole text's index, contract.chunk_spans): refusing that cut is the safe side.
    start = len(plain) - len("30 ml/min")
    assert not quote_edge.edge_before(plain, start, "3")
    walked = "Dose ( + (" + " (" * 300 + " 30"
    assert not quote_edge.edge_before(walked, len(walked) - 2, "3")


def test_the_rules_corners() -> None:
    # An opening mark drawn like a comparator is a sign joined to the quote.
    assert locate_quote("CrCl " + chr(0x2039) + "30 ml/min", "30 ml/min") is None
    # Opening punctuation at the start of the text.
    assert locate_quote("(see below)", "see below") == (1, 10)
    # An empty quote is never found; a text of gaps alone has no number.
    assert locate_quote("x", "") is None
    assert quote_edge.non_gap(chr(0x2009) + " ", 0, 1) is None
    # A cell whose text ends with a gap still holds its words.
    table = "\ufdd0 \ufdd2 \ufdd3 10" + chr(0x2009) + " \ufdd3 000 IU \ufdd1"
    assert locate_quote(table, "000 IU") is None
